import React, { StrictMode, useMemo, useState } from 'react';
import { createRoot } from 'react-dom/client';
import '../styles.css';

const lessons = [
  ['01', 'The board & stones', 'Learn the language of the 9×9 board.', '12 min', 'complete'],
  ['02', 'How to make a move', 'Coordinates, turns, and a legal play.', '8 min', 'complete'],
  ['03', 'Liberties', 'The breathing space every stone needs.', '15 min', 'complete'],
  ['04', 'Capturing stones', 'Spot groups with nowhere left to go.', '18 min', 'in-progress'],
  ['05', 'The ko rule', 'Why a position can’t repeat immediately.', '10 min', 'locked'],
  ['06', 'Life & death', 'Find the eyes that keep groups alive.', '22 min', 'locked']
];

const puzzles = [
  ['capture', 'A clean capture', 'Find the move that takes the last liberty.', 'Capture', 'Beginner', '96%'],
  ['shape', 'The empty triangle', 'Read the shape before you commit.', 'Shape', 'Beginner', '82%'],
  ['eyes', 'Two eyes to live', 'Can this group make enough space?', 'Life & death', 'Easy', '—'],
  ['tesuji', 'The forcing tesuji', 'A sharp move hiding in plain sight.', 'Tesuji', 'Easy', '74%'],
  ['endgame', 'Close the corner', 'Find the biggest endgame point.', 'Endgame', 'Normal', '—']
];

const navItems = [['dashboard', '▦', 'Dashboard'], ['learn', '◒', 'Learn'], ['practice', '◇', 'Practice'], ['play', '⌁', 'Play'], ['statistics', '◌', 'Statistics'], ['profile', '◎', 'Profile']];

function PageHeader({ eyebrow, title, subtitle }) { return <div className="page-heading"><div className="eyebrow">{eyebrow}</div><h1>{title}</h1><p className="page-subtitle">{subtitle}</p></div>; }
function SectionRow({ title, action, onAction, eyebrow }) { return <div className="section-row"><h2>{title}</h2>{action ? <button className="link-button" onClick={onAction}>{action}</button> : eyebrow ? <span className="eyebrow">{eyebrow}</span> : null}</div>; }
function StatCard({ label, value, sub, change }) { return <div className="card stat-card"><div className="stat-label">{label}<span className="stat-change">{change}</span></div><div className="stat-value">{value}</div><div className="stat-label">{sub}</div></div>; }
function Category({ name, value, width, tone }) { return <div className="category-row"><label>{name}</label><b>{value}</b><div className="bar"><i style={{ width: `${width}%`, background: tone }} /></div></div>; }
function GameRow({ date, color, board, level, result, duration, onClick }) { return <tr onClick={onClick}><td>{date}</td><td><span className={`color-disc ${color}`} />{color === 'black' ? 'Black' : 'White'}</td><td>{board}</td><td>{level}</td><td><span className={`result ${result === 'Won' ? 'win' : 'loss'}`}>{result}</span></td><td>{duration}</td></tr>; }

function Dashboard({ navigate }) {
  return <><PageHeader eyebrow="Wednesday · August 27, 2026" title="Good evening, Alex." subtitle="A few thoughtful moves today will keep your reading sharp." />
    <div className="stats-grid"><StatCard label="Current level" value="12" sub="1,160 XP to level 13" change="↗ 8%" /><StatCard label="Games played" value="24" sub="This month" change="↗ 4" /><StatCard label="Win rate" value="62%" sub="Across 24 games" change="↗ 3.2%" /><StatCard label="Learning time" value="6h 42m" sub="This month" change="↗ 18%" /></div>
    <div className="dashboard-grid"><section className="recent-games"><SectionRow title="Recent games" action="View all ↗" onAction={() => navigate('play')} /><div className="card table-card"><table className="game-table"><thead><tr><th>Date</th><th>Color</th><th>Board</th><th>AI level</th><th>Result</th><th>Time</th></tr></thead><tbody><GameRow date="Today, 18:42" color="black" board="9×9" level="Easy" result="Won" duration="23m" onClick={() => navigate('review')} /><GameRow date="Yesterday, 20:16" color="white" board="9×9" level="Beginner" result="Won" duration="16m" onClick={() => navigate('review')} /><GameRow date="Aug 24, 19:03" color="black" board="9×9" level="Normal" result="Lost" duration="31m" onClick={() => navigate('review')} /><GameRow date="Aug 22, 11:28" color="white" board="9×9" level="Easy" result="Won" duration="19m" onClick={() => navigate('review')} /></tbody></table></div></section><section><SectionRow title="Learning progress" action="Open Learn ↗" onAction={() => navigate('learn')} /><div className="card progress-card"><div className="course-progress"><div className="ring"><span>68%</span></div><div className="course-copy"><strong>Foundations of Go</strong><span>8 of 12 lessons complete</span><div className="mini-bar"><i style={{ width: '68%' }} /></div></div></div><div className="category-list"><Category name="Life & Death" value="72%" width={72} /><Category name="Opening" value="43%" width={43} tone="var(--blue)" /><Category name="Endgame" value="61%" width={61} tone="var(--green)" /></div></div><div className="card daily-card"><div className="eyebrow">Daily practice</div><h3>Read one move deeper</h3><p>Solve a short life & death puzzle to earn +30 XP.</p><button className="button primary" onClick={() => navigate('practice')}>Start challenge →</button></div></section></div></>;
}

function Learn() {
  const [filter, setFilter] = useState('All lessons');
  const filtered = lessons.filter((lesson) => filter === 'All lessons' || (filter === 'Completed' && lesson[4] === 'complete') || (filter === 'In progress' && lesson[4] === 'in-progress'));
  return <><PageHeader eyebrow="Your curriculum" title="Learn the shape of good moves." subtitle="Short lessons, clear explanations, and a board to try it yourself." /><div className="section-row"><div className="filter-tabs">{['All lessons', 'In progress', 'Completed'].map((item) => <button key={item} className={`filter-tab ${filter === item ? 'active' : ''}`} onClick={() => setFilter(item)}>{item}</button>)}</div><span className="eyebrow">8 / 12 complete</span></div><div className="lesson-grid">{filtered.map((lesson, index) => <article className="card lesson-card" key={lesson[0]} onClick={() => window.alert(index < 4 ? `${lesson[1]} opened` : 'Complete the previous lesson first')}><span className="lesson-number">LESSON {lesson[0]}</span><h3>{lesson[1]}</h3><p>{lesson[2]}</p><div className="lesson-meta"><span>{lesson[3]}</span><span className={lesson[4] === 'complete' ? 'complete' : ''}>{lesson[4] === 'complete' ? '✓ Complete' : lesson[4] === 'locked' ? '⌁ Locked' : 'Continue →'}</span></div></article>)}</div></>;
}

function PuzzleModal({ puzzle, close, toast }) {
  if (!puzzle) return null;
  return <div className="modal-backdrop open"><div className="modal"><div className="eyebrow">{puzzle[3]} · {puzzle[4]}</div><h2>{puzzle[1]}</h2><p>{puzzle[2]} Click the highlighted-looking point on the mini board to try your read.</p><div className="board-wrap" style={{ borderWidth: 6, padding: 5, marginTop: 18 }}><div className="board" style={{ '--board-grid': '25%', gridTemplateColumns: 'repeat(5,1fr)', gridTemplateRows: 'repeat(5,1fr)' }}>{Array.from({ length: 25 }, (_, index) => <button className="board-cell" key={index}>{[6, 7, 11, 12].includes(index) && <span className={`stone ${index === 12 ? 'white' : 'black'}`} />}</button>)}</div></div><div className="modal-actions"><button className="button ghost" onClick={close}>Not now</button><button className="button primary" onClick={() => { close(); toast('Correct direction — +30 XP earned.'); }}>Try move →</button></div></div></div>;
}

function Practice({ toast }) {
  const [filter, setFilter] = useState('All puzzles'); const [selected, setSelected] = useState(null);
  const filtered = filter === 'All puzzles' ? puzzles : puzzles.filter((puzzle) => puzzle[3] === filter || puzzle[4] === filter);
  return <><PageHeader eyebrow="Tactical reading" title="Practice with purpose." subtitle="Build your intuition one position at a time." /><div className="practice-layout"><section><div className="practice-head"><SectionRow title="Puzzle library" eyebrow={`${puzzles.length} available`} /><div className="practice-filters"><select className="select" value={filter} onChange={(event) => setFilter(event.target.value)}><option>All puzzles</option><option>Capture</option><option>Life & death</option><option>Shape</option><option>Tesuji</option><option>Endgame</option></select><select className="select" defaultValue="Any difficulty"><option>Any difficulty</option><option>Beginner</option><option>Easy</option><option>Normal</option></select></div></div><div className="puzzle-list">{filtered.length ? filtered.map((puzzle, index) => <article className="card puzzle-card" key={puzzle[1]} onClick={() => setSelected(index)}><div className="puzzle-symbol">{puzzle[0] === 'capture' ? '◎' : puzzle[0] === 'eyes' ? '◉' : puzzle[0] === 'tesuji' ? '✣' : puzzle[0] === 'endgame' ? '⌟' : '◇'}</div><div className="puzzle-copy"><h3>{puzzle[1]}</h3><p>{puzzle[2]}</p></div><span className="puzzle-tag">{puzzle[4]}</span><span className="puzzle-score">{puzzle[5]}</span></article>) : <div className="card empty-state">No puzzles match this filter yet.</div>}</div></section><aside className="card practice-side"><h3>Your puzzle profile</h3><Skill label="Solved" value="38 / 52" /><Skill label="Accuracy" value="78%" /><Skill label="Avg. time" value="1m 42s" /><Skill label="Best category" value="Capture" /><button className="button primary" onClick={() => setSelected(0)} style={{ width: '100%', marginTop: 14 }}>Quick solve →</button></aside></div><PuzzleModal puzzle={selected === null ? null : puzzles[selected]} close={() => setSelected(null)} toast={toast} /></>;
}
function Skill({ label, value }) { return <div className="skill-summary"><span>{label}</span><b>{value}</b></div>; }

function Board({ size, stones, lastMove, onCell }) { return <><div className="board" style={{ '--board-grid': `${100 / size}%`, gridTemplateColumns: `repeat(${size},1fr)`, gridTemplateRows: `repeat(${size},1fr)` }}>{Array.from({ length: size * size }, (_, index) => <button className="board-cell" key={index} onClick={() => onCell(index)} aria-label={`Board intersection ${index + 1}`}>{stones[index] && <span className={`stone ${stones[index]} ${lastMove === index ? 'last' : ''}`} />}</button>)}</div><div className="board-info"><span>A B C D E F G H J</span><span>← Your turn</span></div></>; }

function Play({ toast }) {
  const [size, setSize] = useState(9); const [color, setColor] = useState('Black'); const [difficulty, setDifficulty] = useState('Easy'); const [stones, setStones] = useState({}); const [lastMove, setLastMove] = useState(null); const [thinking, setThinking] = useState(false); const [move, setMove] = useState(1);
  const play = (index) => { if (thinking || stones[index]) return; const player = color === 'White' ? 'white' : 'black'; const ai = player === 'black' ? 'white' : 'black'; const next = { ...stones, [index]: player }; setStones(next); setLastMove(index); setMove((current) => current + 1); setThinking(true); toast('Good instinct. Stone placed.'); window.setTimeout(() => { const center = Math.floor(size / 2); const candidates = [center * size + center, center * size + center - 1, (center - 1) * size + center, center * size + center + 1, (center + 1) * size + center]; const aiIndex = candidates.find((candidate) => candidate >= 0 && candidate < size * size && !next[candidate]) ?? Array.from({ length: size * size }, (_, candidate) => candidate).find((candidate) => !next[candidate]); if (aiIndex !== undefined) setStones((current) => ({ ...current, [aiIndex]: ai })); setLastMove(aiIndex); setMove((current) => current + 1); setThinking(false); toast('AI replied. Look for the weakest group.'); }, 520); };
  const reset = () => { setStones({}); setMove(1); setLastMove(null); setThinking(false); toast('New game ready — you have the first move.'); };
  return <><PageHeader eyebrow="Playground" title="A quiet board. A sharp opponent." subtitle="Play a focused 9×9 game and get a useful explanation after every move." /><div className="play-layout"><div className="board-wrap"><Board size={size} stones={stones} lastMove={lastMove} onCell={play} /></div><div className="play-copy"><div className="eyebrow">Live game · {difficulty}{thinking ? ' · AI thinking' : ` · Move ${move}`}</div><h2 style={{ fontSize: 24, margin: '7px 0 10px' }}>Your move, your lesson.</h2><p className="page-subtitle">Kifu watches the position as it develops, then translates the important moments into plain language.</p><div className="card setup-card"><h3>Game setup</h3><OptionGroup label="Board size" options={[9, 13, 19]} value={size} onChange={(value) => { setSize(Number(value)); reset(); }} /><OptionGroup label="Your color" options={['Black', 'White', 'Random']} value={color} onChange={setColor} /><OptionGroup label="AI difficulty" options={['Beginner', 'Easy', 'Normal']} value={difficulty} onChange={setDifficulty} /><div className="setup-footer"><span className="ai-note"><span>●</span> AI analysis on</span><button className="button primary" onClick={reset}>New game →</button></div></div><div className="card live-panel"><SectionRow title="Coach note" eyebrow={`After move ${Math.max(1, move - 1)}`} /><div className="ai-bubble"><i>✦</i><span>{move > 1 ? 'Nice shape. Before your next move, look for the group with fewer liberties.' : 'Your first move sets the tone. Take a breath and scan the corners first.'}</span></div></div></div></div></>;
}
function OptionGroup({ label, options, value, onChange }) { return <><div className="option-label">{label}</div><div className="option-row">{options.map((option) => <button className={`option ${value === option ? 'selected' : ''}`} key={option} onClick={() => onChange(option)}>{option}{typeof option === 'number' ? ' × ' + option : ''}</button>)}</div></>; }

function Statistics() { const breakdown = (label, value, width, tone) => <div className="breakdown-item"><span>{label}</span><b>{value}</b><div className="bar"><i style={{ width: `${width}%`, background: tone }} /></div></div>; return <><PageHeader eyebrow="Your record" title="Progress you can feel." subtitle="A clearer view of the habits behind your games." /><div className="stat-layout"><section><div className="card chart-card"><SectionRow title="Win probability" /><div className="chart-area"><svg className="chart-svg" viewBox="0 0 600 190" preserveAspectRatio="none"><path d="M0 143 C45 127 60 148 95 125 S145 101 181 117 S230 132 260 94 S310 84 341 103 S394 62 427 74 S470 31 506 57 S552 43 600 18" fill="none" stroke="#e7a85e" strokeWidth="3" /><path d="M0 119 C70 111 105 120 155 107 S240 112 300 91 S385 96 440 77 S520 72 600 58" fill="none" stroke="#8db8c8" strokeWidth="2" strokeDasharray="6 6" /><circle cx="506" cy="57" r="5" fill="#e7a85e" stroke="#f5f0e7" strokeWidth="2" /></svg></div><div className="chart-labels"><span>May 28</span><span>Jun 11</span><span>Jun 25</span><span>Jul 09</span><span>Jul 23</span><span>Today</span></div></div><div className="stat-counters"><div className="card counter"><strong>24</strong><span>Games played</span></div><div className="card counter"><strong>15</strong><span>Games won</span></div><div className="card counter"><strong>23m</strong><span>Avg. duration</span></div></div></section><aside className="card breakdown-card"><SectionRow title="Move quality" eyebrow="Last 24 games" /><div className="breakdown-list">{breakdown('Excellent', '18%', 18)}{breakdown('Good', '42%', 42, 'var(--blue)')}{breakdown('Inaccuracy', '25%', 25, 'var(--green)')}{breakdown('Mistake', '11%', 11, '#b893d0')}{breakdown('Blunder', '4%', 4, 'var(--red)')}</div></aside></div></>; }

function Profile({ toast }) { const [toggles, setToggles] = useState({ explanations: true, coordinates: true, reminder: false }); const toggle = (key) => setToggles((current) => ({ ...current, [key]: !current[key] })); const Setting = ({ title, desc, name }) => <div className="settings-row"><div><strong>{title}</strong><span>{desc}</span></div><button className={`toggle ${toggles[name] ? '' : 'off'}`} onClick={() => toggle(name)} aria-label={`Toggle ${title}`} /></div>; return <><PageHeader eyebrow="Your account" title="Make the practice yours." subtitle="Preferences that keep your learning focused." /><div className="profile-layout"><section className="card profile-card"><div className="profile-large">AM</div><h2>Alex Morgan</h2><p>alex.morgan@example.com</p><div className="profile-level"><span>Level 12</span><b>2,840 / 4,000 XP</b></div><div className="bar"><i /></div><div className="profile-facts"><div><span>Member since</span><b>April 2026</b></div><div><span>Games played</span><b>24</b></div><div><span>Current streak</span><b>7 days ✦</b></div></div></section><section className="card settings-card"><h2>Practice preferences</h2><Setting title="AI explanations" desc="Show a short teaching note after each move." name="explanations" /><Setting title="Move coordinates" desc="Keep coordinates visible on the board." name="coordinates" /><Setting title="Daily reminder" desc="A gentle nudge at 7:30 PM." name="reminder" /><div className="settings-row"><div><strong>Account security</strong><span>Password and sign-in options</span></div><button className="button ghost" onClick={() => toast('Security settings are coming soon')}>Manage →</button></div></section></div></>; }

function Review() { const stones = { 10: 'black', 11: 'white', 19: 'black', 20: 'white', 21: 'black', 28: 'white', 29: 'black', 38: 'white', 39: 'black', 48: 'white', 49: 'black', 58: 'black', 59: 'white', 60: 'black', 67: 'white', 68: 'black', 69: 'white' }; const [move, setMove] = useState(12); return <><PageHeader eyebrow="Game review · Today, 18:42" title="Read the moments that mattered." subtitle="A calm replay of your game against Easy AI." /><div className="review-grid"><div className="board-wrap review-board"><div className="board" style={{ '--board-grid': '12.5%', gridTemplateColumns: 'repeat(9,1fr)', gridTemplateRows: 'repeat(9,1fr)' }}>{Array.from({ length: 81 }, (_, index) => <button className="board-cell" key={index}>{stones[index] && <span className={`stone ${stones[index]} ${index === 39 ? 'last' : ''}`} />}</button>)}</div><div className="board-info"><span>A B C D E F G H J</span><span>Move {move} / 24</span></div></div><div className="review-side"><div className="card review-insight"><div className="eyebrow">Move {move} · Your move</div><h2>D5 was a mistake</h2><p>You protected your group, but the move was too slow. White had a weak group in the upper-right corner — <strong style={{ color: 'var(--text)' }}>F6</strong> would have put immediate pressure on it.</p><div className="move-detail"><div><span>Win probability</span><b style={{ color: 'var(--red)' }}>54% → 43%</b></div><div><span>Score loss</span><b style={{ color: 'var(--red)' }}>−3.7 pts</b></div></div></div><div className="review-nav"><button className="button" onClick={() => setMove((current) => Math.max(1, current - 1))}>← Previous</button><button className="button primary" onClick={() => setMove((current) => Math.min(24, current + 1))}>Next →</button></div><div className="card timeline">{Array.from({ length: 12 }, (_, index) => <button className={`move-pill ${index + 1 === move ? 'active' : ''}`} onClick={() => setMove(index + 1)} key={index}>{index + 1}</button>)}</div></div></div></>; }

export function App() { const [page, setPage] = useState('dashboard'); const [sidebarOpen, setSidebarOpen] = useState(false); const [toastMessage, setToastMessage] = useState(''); const toast = (message) => { setToastMessage(message); window.clearTimeout(window.__kifuToast); window.__kifuToast = window.setTimeout(() => setToastMessage(''), 2600); }; const navigate = (next) => { setPage(next); setSidebarOpen(false); window.scrollTo({ top: 0, behavior: 'smooth' }); }; const content = useMemo(() => ({ dashboard: <Dashboard navigate={navigate} />, learn: <Learn />, practice: <Practice toast={toast} />, play: <Play toast={toast} />, statistics: <Statistics />, profile: <Profile toast={toast} />, review: <Review /> }[page]), [page]); return <div className="app-shell"><aside className={`sidebar ${sidebarOpen ? 'open' : ''}`}><div className="brand-row"><div className="brand-mark" aria-hidden="true"><span /><span /><span /><span /></div><div className="brand-name">kifu<span>.</span></div><button className="icon-button sidebar-close" onClick={() => setSidebarOpen(false)} aria-label="Close navigation">×</button></div><div className="profile-mini"><div className="avatar">AM</div><div><strong>Alex Morgan</strong><span>Level 12 · 2,840 XP</span></div><span className="status-dot" /></div><nav className="primary-nav" aria-label="Primary navigation"><p className="nav-label">Workspace</p>{navItems.slice(0, 4).map(([key, icon, label]) => <button className={`nav-item ${page === key ? 'active' : ''}`} key={key} onClick={() => navigate(key)}><span className="nav-icon">{icon}</span>{label}</button>)}<p className="nav-label nav-label-spaced">Your record</p>{navItems.slice(4).map(([key, icon, label]) => <button className={`nav-item ${page === key ? 'active' : ''}`} key={key} onClick={() => navigate(key)}><span className="nav-icon">{icon}</span>{label}</button>)}</nav><div className="sidebar-bottom"><div className="streak-card"><div className="streak-icon">✦</div><div><strong>7 day streak</strong><span>Keep your rhythm going</span></div></div><div className="sidebar-footer"><span>v0.4.2 beta</span><button className="text-button" onClick={() => toast('Help center is coming soon')}>Help ↗</button></div></div></aside><main className="main-content"><header className="topbar"><button className="icon-button menu-toggle" onClick={() => setSidebarOpen(true)} aria-label="Open navigation">☰</button><div className="breadcrumbs"><span>Kifu</span><b>/</b><strong>{page === 'review' ? 'Game Review' : page[0].toUpperCase() + page.slice(1)}</strong></div><div className="topbar-actions"><button className="icon-button notification-button" onClick={() => toast("You're all caught up")} aria-label="Notifications">♧<i /></button><div className="top-avatar">AM</div></div></header><div className="page-container">{content}</div></main>{toastMessage && <div className="toast show" role="status">{toastMessage}</div>}</div>; }

const rootElement = typeof document !== 'undefined' ? document.getElementById('root') : null;
if (rootElement) createRoot(rootElement).render(<StrictMode><App /></StrictMode>);
