import React, { StrictMode, useEffect, useMemo, useState } from 'react';
import { createRoot } from 'react-dom/client';
import { createGame, findAiMove, passMove, playMove, resignGame } from './game/goEngine.js';
import '../styles.css';

const lessons = [
  ['01', 'The board and stones', 'Learn the language of the 9x9 board.', '12 min'],
  ['02', 'How to make a move', 'Coordinates, turns, and a legal play.', '8 min'],
  ['03', 'Liberties', 'The breathing space every stone needs.', '15 min'],
  ['04', 'Capturing stones', 'Spot groups with nowhere left to go.', '18 min'],
  ['05', 'The ko rule', 'Why a position cannot repeat immediately.', '10 min'],
  ['06', 'Life and death', 'Find the eyes that keep groups alive.', '22 min']
];

const navItems = [['dashboard', '[]', 'Dashboard'], ['learn', '◒', 'Learn'], ['practice', '{}', 'Practice'], ['play', '⌁', 'Play'], ['statistics', '◌', 'Statistics'], ['profile', '◎', 'Profile']];

function PageHeader({ eyebrow, title, subtitle }) { return <div className="page-heading"><div className="eyebrow">{eyebrow}</div><h1>{title}</h1><p className="page-subtitle">{subtitle}</p></div>; }
function SectionRow({ title, action, onAction, eyebrow }) { return <div className="section-row"><h2>{title}</h2>{action ? <button className="link-button" onClick={onAction}>{action}</button> : eyebrow ? <span className="eyebrow">{eyebrow}</span> : null}</div>; }
function StatCard({ label, value, sub, change }) { return <div className="card stat-card"><div className="stat-label">{label}<span className="stat-change">{change}</span></div><div className="stat-value">{value}</div><div className="stat-label">{sub}</div></div>; }
function Category({ name, value, width, tone }) { return <div className="category-row"><label>{name}</label><b>{value}</b><div className="bar"><i style={{ width: `${width}%`, background: tone }} /></div></div>; }
function Skill({ label, value }) { return <div className="skill-summary"><span>{label}</span><b>{value}</b></div>; }

function Dashboard({ navigate }) {
  return <><PageHeader eyebrow="Your learning space" title="Ready for your next move?" subtitle="Learn the fundamentals, then test them on the board." />
    <div className="stats-grid"><StatCard label="Current level" value="12" sub="Start learning to earn XP" change="--" /><StatCard label="Games played" value="0" sub="No saved games yet" change="--" /><StatCard label="Win rate" value="--" sub="Play your first game" change="--" /><StatCard label="Learning time" value="0m" sub="No activity recorded" change="--" /></div>
    <div className="dashboard-grid"><section className="recent-games"><SectionRow title="Recent games" action="Play a game →" onAction={() => navigate('play')} /><div className="card table-card"><div className="empty-state"><h3>No games yet</h3><p>Finish a game to see your moves and AI analysis here.</p><button className="button primary" onClick={() => navigate('play')}>Start your first game</button></div></div></section><section><SectionRow title="Learning progress" action="Open Learn →" onAction={() => navigate('learn')} /><div className="card progress-card"><div className="course-progress"><div className="ring"><span>0%</span></div><div className="course-copy"><strong>Foundations of Go</strong><span>Begin with the board and stones</span><div className="mini-bar"><i style={{ width: '0%' }} /></div></div></div><div className="category-list"><Category name="Life and death" value="--" width={0} /><Category name="Opening" value="--" width={0} tone="var(--blue)" /><Category name="Endgame" value="--" width={0} tone="var(--green)" /></div></div><div className="card daily-card"><div className="eyebrow">Suggested next step</div><h3>Start with the basics</h3><p>Learn how liberties work before your first match.</p><button className="button primary" onClick={() => navigate('learn')}>Open Learn →</button></div></section></div></>;
}

function Learn() {
  return <><PageHeader eyebrow="Your curriculum" title="Learn the shape of good moves." subtitle="A focused course catalog for the fundamentals of Go." /><div className="section-row"><h2>Course catalog</h2><span className="eyebrow">6 lessons</span></div><div className="lesson-grid">{lessons.map((lesson) => <article className="card lesson-card" key={lesson[0]}><span className="lesson-number">LESSON {lesson[0]}</span><h3>{lesson[1]}</h3><p>{lesson[2]}</p><div className="lesson-meta"><span>{lesson[3]}</span><span>Available</span></div></article>)}</div></>;
}

function Practice() {
  return <><PageHeader eyebrow="Tactical reading" title="Practice with purpose." subtitle="Puzzle content will appear here when the practice API is connected." /><div className="practice-layout"><section><div className="practice-head"><SectionRow title="Puzzle library" eyebrow="No puzzles loaded" /><div className="practice-filters"><select className="select" disabled defaultValue="All puzzles"><option>All puzzles</option></select><select className="select" disabled defaultValue="Any difficulty"><option>Any difficulty</option></select></div></div><div className="card empty-state"><h2>No puzzles yet</h2><p>Connect the puzzle service to load positions, attempts, and explanations.</p></div></section><aside className="card practice-side"><h3>Your puzzle profile</h3><Skill label="Solved" value="--" /><Skill label="Accuracy" value="--" /><Skill label="Avg. time" value="--" /><Skill label="Best category" value="--" /></aside></div></>;
}

function starPoints(size) { if (size === 9) return [20, 24, 40, 56, 60]; if (size === 13) return [42, 48, 84, 120, 126]; return [57, 63, 69, 117, 123, 129, 177, 183, 189]; }
function coordinates(size) { return Array.from({ length: size }, (_, index) => String.fromCharCode(65 + index + (index >= 8 ? 1 : 0))); }
function Board({ game, onCell, disabled = false }) { const coords = coordinates(game.size); const stars = starPoints(game.size); const step = 100 / (game.size - 1); return <><div className="board" style={{ '--board-step': `${step}%` }}>{game.board.map((stone, index) => { const row = Math.floor(index / game.size); const col = index % game.size; return <button className="board-cell" disabled={disabled} key={index} style={{ left: `${col * step}%`, top: `${row * step}%` }} onClick={() => onCell(index)} aria-label={`Board intersection ${coords[col]}${game.size - row}`}>{stars.includes(index) && <span className="board-star" />}{stone && <span className={`stone ${stone} ${game.lastMove === index ? 'last' : ''}`} />}</button>; })}</div><div className="board-info"><span>{coords.join(' ')}</span><span>{game.status === 'active' ? `${game.currentPlayer === 'black' ? 'Black' : 'White'} to play` : 'Game finished'}</span></div></>; }

function Play({ toast }) {
  const [size, setSize] = useState(9); const [selectedColor, setSelectedColor] = useState('Black'); const [userColor, setUserColor] = useState('black'); const [difficulty, setDifficulty] = useState('Easy'); const [game, setGame] = useState(() => createGame(9)); const [aiBusy, setAiBusy] = useState(false);
  const startGame = (nextSize = size, nextColor = selectedColor) => { const resolved = nextColor === 'Random' ? (Math.random() < 0.5 ? 'Black' : 'White') : nextColor; setSize(Number(nextSize)); setSelectedColor(nextColor); setUserColor(resolved.toLowerCase()); setGame(createGame(Number(nextSize))); setAiBusy(false); toast(`${resolved} selected. Standard Go starts with Black.`); };
  useEffect(() => { if (game.status !== 'active' || game.currentPlayer === userColor || aiBusy) return undefined; const timer = window.setTimeout(() => { setAiBusy(true); const index = findAiMove(game); if (index === null) { const passed = passMove(game); setGame(passed.game); } else { const result = playMove(game, index); if (!result.error) setGame(result.game); } setAiBusy(false); toast('AI replied. Look for the weakest group.'); }, 520); return () => window.clearTimeout(timer); }, [game, userColor, aiBusy, toast]);
  const onCell = (index) => { if (aiBusy || game.status !== 'active' || game.currentPlayer !== userColor) return; const result = playMove(game, index); if (result.error) { const messages = { occupied: 'That intersection is occupied.', suicide: 'That move would be suicide.', ko: 'Ko: this position cannot be repeated yet.' }; toast(messages[result.error] || 'Illegal move.'); return; } setGame(result.game); toast('Move accepted. AI is reading the position.'); };
  const onPass = () => { if (game.currentPlayer !== userColor || game.status !== 'active') return; const result = passMove(game); setGame(result.game); toast(result.game.status === 'finished' ? 'Two passes: the game is finished.' : 'Pass recorded.'); };
  const onResign = () => { if (game.currentPlayer !== userColor || game.status !== 'active') return; const result = resignGame(game); setGame(result.game); toast('Game resigned.'); };
  const aiTurn = aiBusy || (game.status === 'active' && game.currentPlayer !== userColor);
  return <><PageHeader eyebrow="Playground" title="A quiet board. A sharp opponent." subtitle="Black opens by rule. Choose White to let the AI make the first move." /><div className="play-layout"><div className="board-wrap"><Board game={game} onCell={onCell} disabled={aiTurn || game.status !== 'active'} /></div><div className="play-copy"><div className="eyebrow">Live game · {difficulty}{aiTurn ? ' · AI thinking' : ` · Move ${game.moveNumber}`}</div><h2 style={{ fontSize: 24, margin: '7px 0 10px' }}>{game.status === 'active' ? `${userColor === 'black' ? 'Black' : 'White'} stones, clearer thinking.` : game.winner === 'draw' ? 'A draw by territory.' : 'Game complete.'}</h2><p className="page-subtitle">Kifu validates liberties, captures, suicide, ko, turns, passes, resignation, and area scoring in the game engine.</p><div className="card setup-card"><h3>Game setup</h3><OptionGroup label="Board size" options={[9, 13, 19]} value={size} onChange={(value) => startGame(value, selectedColor)} /><OptionGroup label="Your color" options={['Black', 'White', 'Random']} value={selectedColor} onChange={(value) => startGame(size, value)} /><OptionGroup label="AI difficulty" options={['Beginner', 'Easy', 'Normal']} value={difficulty} onChange={setDifficulty} /><div className="setup-footer"><span className="ai-note"><span>●</span> Rules engine on</span><div className="game-actions"><button className="button ghost" onClick={onPass}>Pass</button><button className="button ghost" onClick={onResign}>Resign</button><button className="button primary" onClick={() => startGame()}>New game</button></div></div></div><div className="card live-panel"><SectionRow title="Coach note" eyebrow={aiTurn ? 'AI is reading' : `Move ${game.moveNumber}`} /><div className="ai-bubble"><i>✦</i><span>{game.status !== 'active' ? 'Review and scoring will be available after backend persistence is connected.' : aiTurn ? 'The AI is checking the legal replies.' : 'Before your next move, look for the group with fewer liberties.'}</span></div></div></div></div></>;
}
function OptionGroup({ label, options, value, onChange }) { return <><div className="option-label">{label}</div><div className="option-row">{options.map((option) => <button className={`option ${value === option ? 'selected' : ''}`} key={option} onClick={() => onChange(option)}>{option}{typeof option === 'number' ? ` x ${option}` : ''}</button>)}</div></>; }

function Statistics() { return <><PageHeader eyebrow="Your record" title="Progress you can feel." subtitle="Your stats will appear here after your first completed game." /><div className="card empty-state empty-statistics"><h2>No statistics yet</h2><p>Play a game or complete a lesson to start building your record.</p><button className="button primary">Statistics will update automatically</button></div></>; }
function Profile({ toast }) { const [toggles, setToggles] = useState({ explanations: true, coordinates: true, reminder: false }); const toggle = (key) => setToggles((current) => ({ ...current, [key]: !current[key] })); const Setting = ({ title, desc, name }) => <div className="settings-row"><div><strong>{title}</strong><span>{desc}</span></div><button className={`toggle ${toggles[name] ? '' : 'off'}`} onClick={() => toggle(name)} aria-label={`Toggle ${title}`} /></div>; return <><PageHeader eyebrow="Your account" title="Make the practice yours." subtitle="Sign in later to save progress across devices." /><div className="profile-layout"><section className="card profile-card"><div className="profile-large">?</div><h2>Guest learner</h2><p>No account connected</p><div className="profile-level"><span>Level 1</span><b>0 XP</b></div><div className="bar"><i style={{ width: '0%' }} /></div><div className="profile-facts"><div><span>Games played</span><b>0</b></div><div><span>Lessons completed</span><b>0</b></div><div><span>Puzzles solved</span><b>0</b></div></div></section><section className="card settings-card"><h2>Practice preferences</h2><Setting title="AI explanations" desc="Show a short teaching note after each move." name="explanations" /><Setting title="Move coordinates" desc="Keep coordinates visible on the board." name="coordinates" /><Setting title="Daily reminder" desc="A gentle nudge at a time you choose." name="reminder" /><div className="settings-row"><div><strong>Account</strong><span>Registration and sign-in will be connected to the API.</span></div><button className="button ghost" onClick={() => toast('Authentication is not connected yet')}>Coming soon</button></div></section></div></>; }
function Review() { return <><PageHeader eyebrow="Game review" title="Review comes after your first game." subtitle="Complete a saved game to inspect moves, evaluations, and explanations." /><div className="card empty-state"><h2>No saved games to review</h2><p>Start from Play. Your review timeline will appear here once persistence is connected.</p></div></>; }

export function App() { const [page, setPage] = useState('dashboard'); const [sidebarOpen, setSidebarOpen] = useState(false); const [toastMessage, setToastMessage] = useState(''); const toast = (message) => { setToastMessage(message); window.clearTimeout(window.__kifuToast); window.__kifuToast = window.setTimeout(() => setToastMessage(''), 2600); }; const navigate = (next) => { setPage(next); setSidebarOpen(false); window.scrollTo({ top: 0, behavior: 'smooth' }); }; const content = useMemo(() => ({ dashboard: <Dashboard navigate={navigate} />, learn: <Learn />, practice: <Practice toast={toast} />, play: <Play toast={toast} />, statistics: <Statistics />, profile: <Profile toast={toast} />, review: <Review /> }[page]), [page]); return <div className="app-shell"><aside className={`sidebar ${sidebarOpen ? 'open' : ''}`}><div className="brand-row"><div className="brand-mark" aria-hidden="true"><span /><span /><span /><span /></div><div className="brand-name">kifu<span>.</span></div><button className="icon-button sidebar-close" onClick={() => setSidebarOpen(false)} aria-label="Close navigation">x</button></div><div className="profile-mini"><div className="avatar">?</div><div><strong>Guest learner</strong><span>Progress not saved</span></div><span className="status-dot" /></div><nav className="primary-nav" aria-label="Primary navigation"><p className="nav-label">Workspace</p>{navItems.slice(0, 4).map(([key, icon, label]) => <button className={`nav-item ${page === key ? 'active' : ''}`} key={key} onClick={() => navigate(key)}><span className="nav-icon">{icon}</span>{label}</button>)}<p className="nav-label nav-label-spaced">Your record</p>{navItems.slice(4).map(([key, icon, label]) => <button className={`nav-item ${page === key ? 'active' : ''}`} key={key} onClick={() => navigate(key)}><span className="nav-icon">{icon}</span>{label}</button>)}</nav><div className="sidebar-bottom"><div className="streak-card"><div className="streak-icon">✦</div><div><strong>No streak yet</strong><span>Complete your first activity</span></div></div><div className="sidebar-footer"><span>v0.4.2 beta</span><button className="text-button" onClick={() => toast('Help center is not connected yet')}>Help ↗</button></div></div></aside><main className="main-content"><header className="topbar"><button className="icon-button menu-toggle" onClick={() => setSidebarOpen(true)} aria-label="Open navigation">☰</button><div className="breadcrumbs"><span>Kifu</span><b>/</b><strong>{page === 'review' ? 'Game Review' : page[0].toUpperCase() + page.slice(1)}</strong></div><div className="topbar-actions"><button className="icon-button notification-button" onClick={() => toast('No notifications yet')} aria-label="Notifications">♧<i /></button><div className="top-avatar">?</div></div></header><div className="page-container">{content}</div></main>{toastMessage && <div className="toast show" role="status">{toastMessage}</div>}</div>; }

const rootElement = typeof document !== 'undefined' ? document.getElementById('root') : null;
if (rootElement) createRoot(rootElement).render(<StrictMode><App /></StrictMode>);
